Milestone 2: Add aboutme and works section
isume295/My_Portfolio pull request #2
Opened 2023-03-24 23:07 UTC by isume295

In this milestone I:
-Add about me page
-Add workers page
-Add contact me page

2023-03-24 23:41 UTC, huseyinbiyik requested changes
Hi @sumeya8 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Grid and flexbox are used very well 👍 
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 23:41 UTC, huseyinbiyik commented on index.html
> +           <h1 class="projecTitle txtWrapper">Tonic</h1>
Good job with using a heading tag. But you should use your h1 tag only once on a page. For this project, I am Sumeye, Glad to see you needs to be wrapped with h1 tag. All the others can use hx elements hierarchially. Please fix the related area on each card. Heading elements are important to configurate the importance of element on the page and they have a crucial role on SEO and accessibility onf your web pages.

2023-03-24 23:41 UTC, huseyinbiyik commented on index.html
> +            <a class="connectMeLink" href="">LET’S CONNECT</a>
You are right, `Let's connect` looks like a link here but actually it is a heading element of the social links. Kindly use hierarchically correct hx elements for it to make the page more semantic.

2023-03-24 23:41 UTC, huseyinbiyik commented on index.html
> +                <a href=""><svg width="18" height="20" viewBox="0 0 18 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Kindly use semantic `ul` element for wrapping the social media container and use `li` for each `a` element which include the link of social medium.

2023-03-25 03:08 UTC, Shedrack-Sunday approved these changes
# STATUS: APPROVED ♻️♻️
Hi @isume295 

To highlight 👍🏽
✔️ Good semantic implementation
✔️ No linter errors

Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-25 05:07 UTC, merged